### ISSUE TITLE
Nginx onStart handler should not include reload

### ISSUE THREAD

**Issue by tgross** [tgross/triton-nginx#6]
> @lguminski the expected behavior of the `onStart` handler is to return its exit code before we start the main application. In the `onStart` handler (but not the `onChange` handler) we should remove the `nginx -s reload` so that it reads as follows:

ref https://github.com/joyent/containerbuddy/issues/110

@misterbisson said:
> This calls https://github.com/tgross/triton-nginx/blob/master/bin/reload.sh#L19, causing it to try nginx -s reload before the Nginx starts, triggering an error

ref https://github.com/tgross/triton-elk/pull/2#discussion_r56562539

**Comment by misterbisson** [comment]
:house_with_garden: :walking:

**Comment by tgross** [comment]
https://github.com/tgross/triton-nginx/issues/7 was merged. Closing.
